### PR TITLE
Fixed legend

### PR DESCRIPTION
**Pull request by dzanaga**
Fixed a couple of entries for the legend.

In principle the timestamp should also be different. v100 should have `extent: ee.extent_global('2020-01-01T00:00:00Z', '2021-01-01T00:00:00Z'),` and v200 `extent: ee.extent_global('2021-01-01T00:00:00Z', '2022-01-01T00:00:00Z'),`. Not sure how to fix that.

### CODE REVIEW

**Comment by schwehr** [comment]
Thanks for the pull request!

71ece5df15fcebeea8d061ac3d36c5b6eaccdd95 by @simonff handled the dates for the two files. 

For this change, do you mean to change the band names for both datasets or just one of them?  If just one, that would be the newer v200, correct?

**Comment by dzanaga** [comment]
Thanks for fixing the dates!

For the legend change we want to change it on both datasets. These are the correct names we use also in the documentation for both of them.

**Comment by schwehr** [comment]
Then it looks like the non-date part of this commit should be good to go.  We have couple different ways we can go. 

I'm up for which ever you choose:

1. You resolve the conflict yourself
1. I can try to do the resolve for you (I've not done it this way before, so I'll be learning).  
1. You can make a new PR to avoid worrying about the conflict and we just close this one
1. I can make a quick commit to do it separately

If you try 1 and get stuck, it's not a big deal with a change of this scale.  We can then switch to one of the other strategies.

**Comment by schwehr** [comment]
I created #185 where I branched off your change and did the rebase and merge.  If that is ok, let me know and we can put that in.  For the teams general notes, here are the commands that I ran in a clone of my personal fork

```bash
git checkout main
git pull
git remote add dzanaga-remote https://github.com/dzanaga/earthengine-catalog.git
git fetch dzanaga-remote
git checkout -b  dzanaga dzanaga-remote/main
git remote remove dzanaga-remote
git rebase main
# Edit the file to fix the conflict
git add catalog/ESA/worldcover.libsonnet
bazel test //checker/...
git rebase --continue
git push origin dzanaga
```

Then opened the given link to make the pr: https://github.com/schwehr/earthengine-catalog/pull/new/dzanaga

**Comment by dzanaga** [comment]
Thanks, it was holiday here (in Belgium) on Friday, so I just got to see this now. Good for me!

**Comment by schwehr** [comment]
#185 is merged → 03b3a42b1570a1cfcb4ad7ca40a2242f452d8938

**Pull request closed without merging**
